version: '3.4'

services:
  build_image:
    build:
      context: ../../
      dockerfile: docker/backend/Dockerfile
      target: "${BUILD_TARGET:?err}"
    image: "${DOCKERHUB_USERNAME:?err}/knowledge_gpt_${BUILD_TARGET:?err}:${BUILD_TAG_NAME:?err}"
