version: '3.4'

services:
  tests_build:
    build:
      context: ../../
      dockerfile: docker/backend/Dockerfile
      target: "${BUILD_TARGET}"
    image: "${DOCKERHUB_USERNAME}/knowledge_gpt_${BUILD_TARGET}:${TAG_NAME}"
